name: Quick check

on: [pull_request, workflow_dispatch]

jobs:
  stable:
    permissions: {}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --features unstable

  nightly:
    permissions: {}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt --check
      - run: cargo +nightly test --all-features
